# Generated by Django 4.1.1 on 2022-11-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesaj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hizmetTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='doktor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doktor İsmi'),
        ),
        migrations.AddField(
            model_name='post',
            name='alinanHizmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesaj.hizmettur', verbose_name='Alınan Hizmet Türü'),
        ),
    ]
