# Generated by Django 4.1.1 on 2022-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaj', '0002_hizmettur_post_doktor_post_alinanhizmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sikayetTarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
