# Generated by Django 4.1.1 on 2022-12-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaj', '0003_alter_post_sikayettarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hizmettur',
            options={'verbose_name': 'Hizmet Türü', 'verbose_name_plural': 'Hizmet Türleri'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AlterModelOptions(
            name='tur',
            options={'verbose_name': 'Şikayet Tür', 'verbose_name_plural': 'Şikayet Türleri'},
        ),
        migrations.AddField(
            model_name='post',
            name='ad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adınız(İsteğe Bağlı)'),
        ),
    ]
